sudo: required
dist: trusty
language: generic
env:
  - ROS_DISTRO=hydro  USE_DEB=true USE_JENKINS=true
  - ROS_DISTRO=indigo USE_DEB=true USE_JENKINS=false
  - ROS_DISTRO=jade   USE_DEB=true USE_JENKINS=false
matrix:
  allow_failures:
    - env: ROS_DISTRO=jade   USE_DEB=true
script: source .travis/travis.sh
before_script:
  - export ROS_PARALLEL_JOBS="-j2 -l2"
notifications:
  email:
    on_success: always
    on_failure: always
